---
- name: reset install
  hosts: all
  become: True
  gather_facts: True
  tasks:
  - name: uninstall kubernetes components
    apt: name={{ item }} state=absent allow_unauthenticated=yes
    with_items:
      - kubectl
      - kubeadm
      - kubelet
      - docker.io
  - file: path=/etc/kubernetes state=absent
  - file: path=/etc/kubectl state=absent
  - file: path=/etc/kubeadm-join.sh state=absent
  - file: path=/var/lib/etcd state=absent
