---
- name: prepare all (master and nodes)
  hosts: all
  become: True
  gather_facts: True
  roles:
    - { role: 'prepare', tags: 'prepare' }

- name: initialize master
  hosts: masters
  become: True
  gather_facts: False
  roles:
    - { role: 'master', tags: 'master' }

- name: setup nodes
  hosts: all
  become: True
  gather_facts: False
  vars:
    master_hostname: "{{ groups['masters'][0] }}"
  roles:
    - { role: 'nodes', tags: 'nodes' }
