---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc-cip
  labels:
    app: hello
  namespace: hello
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5010
    targetPort: 5000
  selector:
    app: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc-lb
  labels:
    app: hello
  namespace: hello
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5020
    targetPort: 5000
  selector:
    app: hello
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc-np
  labels:
    app: hello
  namespace: hello
spec:
  type: NodePort
  ports:
  - name: http
    port: 5030
    targetPort: 5000
  selector:
    app: hello
---
