---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-sa
  namespace: hello-ns
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-v1
  namespace: hello-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      serviceAccountName: hello-sa
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-v2
  namespace: hello-ns
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      serviceAccountName: hello-sa
      containers:
      - name: helloworld
        image: istio/examples-helloworld-v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc-np
  labels:
    app: hello
  namespace: hello-ns
spec:
  type: NodePort
  ports:
  - name: http
    port: 5002
    targetPort: 5000
  selector:
    app: hello
---
