---
apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
  namespace: hello-ns
spec:
  type: NodePort
  ports:
  - port: 5002
    targetPort: 5000
    name: http
  selector:
    app: hello
---
