- name: Update deb repositories cache and install 'apt-transport-https' package
  apt:
    name: apt-transport-https
    update_cache: yes   ## equivalent of apt-get update

- name: Add the apt/deb K8s repository
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes-xenial

#- name: Remove previous installation of kubernetes components (kubelet, kubeadm, kubectl)
#  apt:
#    name: '{{ item }}'
#    state: absent
#  with_items:
#    - kubelet
#    - kubeadm
#    - kubectl

- name: Install Docker and K8s components (kubelet, kubeadm, kubectl) and ntp
  apt:
    name: '{{ item }}'
    state: present
    allow_unauthenticated: yes
  with_items:
    - docker.io
    - kubelet={{ _k8s_version }}-{{ _k8s_version_deb_min }}
    - kubeadm={{ _k8s_version }}-{{ _k8s_version_deb_min }}
    - kubectl={{ _k8s_version }}-{{ _k8s_version_deb_min }}
    - ntp
