- name: Install modules into Linux Kernel
  command: modprobe {{ item }}
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4

- name: Update '/etc/modules' file
  lineinfile:
    path: /etc/modules
    line: '{{ item }}'
    create: yes
    state: present
  with_items:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  - nf_conntrack_ipv4
