---
- name: merge kubeconfig of your kubernetes clusters
  hosts: k8smasters
  #become: True
  gather_facts: True

  tasks:
  - name: get the remote kubeconfig file
    fetch:
      src: /home/k8sadmin/.kube/config
      dest: /tmp/kubeconfigs    ## /tmp/kubeconfigs/<hostname>/home/k8sadmin/.kube/config

  - name: duplicate the kubeconfig file
    copy:
      remote_src: no
      src: '/tmp/kubeconfigs/{{ inventory_hostname_short }}/home/k8sadmin/.kube/config'
      dest: '~/.kube/{{ inventory_hostname_short }}.kubeconfig'
      force: yes
    delegate_to: 127.0.0.1

  - name: update kubeconfig file
    lineinfile:
      path: '~/.kube/{{ inventory_hostname_short }}.kubeconfig'
      regexp: '{{ item.x }}'
      line: '{{ item.y }}'
      state: present
      backrefs: yes
    with_items:
      - { x: '^(\s+)server: https://{{ ansible_ssh_host }}:6443$', y: '\1server: https://{{ inventory_hostname_short }}:{{ k8s_api_srv_tunneled_port }}' }
      - { x: '^(\s+)name: kubernetes$', y: '\1name: {{ clusterid }}' }
      - { x: '^(\s+)cluster: kubernetes$', y: '\1cluster: {{ clusterid }}' }
      - { x: '^(\s+)user: kubernetes-admin$', y: '\1user: {{ clusterid }}-admin' }
      - { x: '^(\s+)name: kubernetes-admin@kubernetes$', y: '\1name: {{ clusterid }}-admin@{{ clusterid }}' }
      - { x: '^current-context: kubernetes-admin@kubernetes$', y: '#current-context: {{ clusterid }}-admin@{{ clusterid }}' }
      - { x: '^- name: kubernetes-admin$', y: '- name: {{ clusterid }}-admin' }
    delegate_to: 127.0.0.1
