---
- name: Prepare all (master and nodes)
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: ../../ansible-roles/prepare
      tags: 'prepare'

- name: Initialize master
  hosts: masters
  become: True
  gather_facts: False
  roles:
    - role: ../../ansible-roles/master
      tags: 'master'

- name: Setup workers
  hosts: all
  become: True
  gather_facts: False
  vars:
    master_hostname: "{{ groups['masters'][0] }}"
  roles:
    - role: ../../ansible-roles/nodes
      tags: 'nodes'
