---
- name: prepare all (master and nodes)
  hosts: all
  become: yes

  #roles:
  #  - role: ../../ansible/roles/prepare

  tasks:
    - apt_repository:
        repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
        state: present
        filename: kubernetes-xenial

    - apt: name={{ item }} state=present allow_unauthenticated=yes
      with_items:
        #- docker.io
        - kubelet
        - kubeadm
        - kubectl
        #- ntp
      environment:
        http_proxy: http://10.0.11.1:3128
        https_proxy: http://10.0.11.1:3128

  #pre_tasks:
  #  - name: install python2
  #    raw: sudo apt-get -y install python-simplejson
  #    environment:
  #      http_proxy: http://10.0.11.1:3128
